### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lasermat** [Odyrac/SBSniper#4]
juste comme ça comment on fait pour redem le bot pour mettre les mise a jour que l'on a fait

**Comment by Odyrac** [comment]
dis-toi que le bot lorsqu'il tourne sur ton ordi = application cmd. tu veux éteindre le bot ? ferme l'appli cmd. le redémarrer ? tu fais ctrl + c sur la cmd (ça coupe le programme en cours), puis tu refais la commande pour le démarrer.

**Comment by Odyrac** [comment]
hésite pas à star le projet pour soutenir ;)
